config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :submissions
  resources :assignments
  resources :enrollments
  resources :students do
    member { get "example", to: "students/example#pure_sidekiq_job" }
  end
  resources :courses
  resources :teachers
  resources :departments
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :assignment
  belongs_to :student
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[show edit update destroy]

  # GET /submissions
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  def create
    @submission = Submission.new(submission_params)

    if @submission.save
      redirect_to @submission, notice: "Submission was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /submissions/1
  def update
    if @submission.update(submission_params)
      redirect_to @submission, notice: "Submission was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /submissions/1
  def destroy
    @submission.destroy
    redirect_to submissions_url,
                notice: "Submission was successfully destroyed.",
                status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def submission_params
    params.require(:submission).permit(
      :assignment_id,
      :student_id,
      :submitted_at,
      :file_path
    )
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :assignment_id, style: "display: block" %>
    <%= form.text_field :assignment_id %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :submitted_at, style: "display: block" %>
    <%= form.date_field :submitted_at %>
  </div>

  <div>
    <%= form.label :file_path, style: "display: block" %>
    <%= form.text_field :file_path %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
  <p>
    <strong>assignment:</strong>
    <%= submission.assignment_id %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= submission.student_id %>
  </p>

  <p>
    <strong>Submitted at:</strong>
    <%= submission.submitted_at %>
  </p>

  <p>
    <strong>File path:</strong>
    <%= submission.file_path %>
  </p>

</div>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Submissions</h1>

<div id="submissions">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <p>
      <%= link_to "Show this submission", submission %>
    </p>
  <% end %>
</div>

<%= link_to "New submission", new_submission_path %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @submission %>

<div>
  <%= link_to "Edit this submission", edit_submission_path(@submission) %> |
  <%= link_to "Back to submissions", submissions_path %>

  <%= button_to "Destroy this submission", @submission, method: :delete %>
</div>