config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :submissions
  resources :assignments
  resources :enrollments
  resources :students do
    member { get "example", to: "students/example#pure_sidekiq_job" }
  end
  resources :courses
  resources :teachers
  resources :departments
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department, foreign_key: 'department_id'
  has_many :courses
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher, notice: "Teacher was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /teachers/1
  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: "Teacher was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /teachers/1
  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: "Teacher was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :email, :department_id_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :department_id_id, style: "display: block" %>
    <%= form.text_field :department_id_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p>
    <strong>First name:</strong>
    <%= teacher.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= teacher.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= teacher.email %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= teacher.department_id_id %>
  </p>

</div>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teachers</h1>

<div id="teachers">
  <% @teachers.each do |teacher| %>
    <%= render teacher %>
    <p>
      <%= link_to "Show this teacher", teacher %>
    </p>
  <% end %>
</div>

<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>